#!/bin/sh
set -e

if [ -d "$CODESPACE_VSCODE_FOLDER/runner" ]; then
  umount $CODESPACE_VSCODE_FOLDER/runner || true
  rmdir $CODESPACE_VSCODE_FOLDER/runner
fi

runner_path=$(sed 's/\r//g' ~/runner-path)
mkdir $CODESPACE_VSCODE_FOLDER/runner
sshfs runner:$runner_path $CODESPACE_VSCODE_FOLDER/runner