#!/bin/sh

chmod 600 ~/codespaces.auto

cat <<EOF > ~/.ssh/config
Host runner
    Hostname localhost
    Port 4748
    User $(cat ~/runner-user)
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    IdentityFile ~/codespaces.auto
EOF

chmod 600 /root/.ssh/config

if [ -d "runner" ]; then
  umount runner || true
  rmdir runner
fi

runner_path=$(sed 's/\r//g' ~/runner-path)
mkdir runner
sshfs runner:$runner_path runner

tail -f /dev/null

exit 0
