on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - run: |
        gh cs list
        ls -all /home/runner/.ssh/
        gh cs ssh list
        ls -all /home/runner/.ssh/
      env:
        GH_TOKEN: ${{ secrets.TOKEN_FOR_CODESPACES }}