name: macos

on:
  workflow_dispatch:
    inputs:
      codespace:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  connect-to-codespace:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
        netstat -ln
        ls -all ~/.ssh
        ssh-keygen -N '' -f ~/.ssh/id_ecdsa -t ecdsa -b 521
        cat ~/.ssh/id_ecdsa.pub >> ~/.ssh/authorized_keys
        cat <<EOF >> ~/.ssh/config
        Host codespace
            HostName cs.${{ inputs.codespace }}.main
            User root
            Port 4748
            ServerAliveInterval 60
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ProxyCommand /usr/bin/c cs ssh -c ${{ inputs.codespace }} --stdio -- -i ~/.ssh/id_ecdsa
            IdentityFile ~/.ssh/id_ecdsa
        EOF
        which gh
      env:
        GH_TOKEN: ${{ secrets.TOKEN_FOR_CODESPACES }}