name: macos

on:
  workflow_dispatch:
    inputs:
      codespace:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  connect-to-codespace:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        ssh-keygen -N '' -f ~/.ssh/id_ed25519 -t ed25519
        cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
        cat <<EOF >> ~/.ssh/config
        Host codespace
            HostName cs.${{ inputs.codespace }}.main
            User root
            Port 4748
            ServerAliveInterval 60
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ProxyCommand /usr/local/bin/gh cs ssh -c ${{ inputs.codespace }} --stdio -- -i ~/.ssh/id_ed25519
            IdentityFile ~/.ssh/id_ed25519
        EOF
        scp ~/.ssh/id_ed25519 codespace:
        echo $PWD > /tmp/runner-path
        scp /tmp/runner-path codespace:
        ssh -R 4748:localhost:22 codespace 'perl -MPOSIX -e pause'
      name: Setup SSH
      env:
        GH_TOKEN: ${{ secrets.TOKEN_FOR_CODESPACES }}