name: ubuntu

on:
  workflow_dispatch:
    inputs:
      codespace:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  connect-to-codespace:
    runs-on: ubuntu-latest

    steps:
    - run: |
        gh cs ssh -c ${{ inputs.codespace }} true
        cat ~/.ssh/codespaces.auto.pub >> ~/.ssh/authorized_keys
        cat <<EOF >> ~/.ssh/config
        Host codespace
            HostName cs.${{ inputs.codespace }}.main
            User root
            ServerAliveInterval 60
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ProxyCommand /usr/bin/gh cs ssh -c ${{ inputs.codespace }} --stdio -- -i ~/.ssh/codespaces.auto
            IdentityFile ~/.ssh/codespaces.auto
        EOF
        scp ~/.ssh/codespaces.auto codespace:
        echo $PWD > /tmp/runner-path
        scp /tmp/runner-path codespace:
        whoami > /tmp/runner-user
        scp /tmp/runner-user codespace:
        printf "\ncd $PWD\n" >> ~/.bash_profile
        ssh -R 4748:localhost:22 codespace runner-connect
      name: Setup SSH
      env:
        GH_TOKEN: ${{ secrets.TOKEN_FOR_CODESPACES }}