name: windows

on:
  workflow_dispatch:
    inputs:
      codespace:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  connect-to-codespace:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Start-Service sshd
      name:  Start SSH Server

    - run: |
        gh cs ssh -c ${{ inputs.codespace }} true
        type %USERPROFILE%\.ssh\codespaces.auto.pub > %USERPROFILE%\.ssh\authorized_keys
        move /y %USERPROFILE%\.ssh\authorized_keys %ALLUSERSPROFILE%\ssh\administrators_authorized_keys
        (
        echo Host codespace
        echo     HostName cs.${{ inputs.codespace }}.main
        echo     User root
        echo     ServerAliveInterval 60
        echo     StrictHostKeyChecking no
        echo     UserKnownHostsFile /dev/null
        echo     ProxyCommand C:\Program Files\GitHub CLI\gh.exe cs ssh -c ${{ inputs.codespace }} --stdio -- -i %USERPROFILE%\.ssh\codespaces.auto
        echo     IdentityFile %USERPROFILE%\.ssh\codespaces.auto
        ) > %USERPROFILE%\.ssh\config
        scp %USERPROFILE%\.ssh\codespaces.auto codespace:
        echo %cd% > %TEMP%\runner-path
        scp %TEMP%\runner-path codespace:
        whoami > %TEMP%\runner-user
        scp TEMP%\runner-user codespace:
        ssh -R 4748:localhost:22 codespace runner-connect
      shell: cmd
      name: Setup SSH
      env:
        GH_TOKEN: ${{ secrets.TOKEN_FOR_CODESPACES }}